# Used as reference in building this Travis-CI configuration
# https://github.com/simonmichael/hledger/blob/master/.travis.yml
language: bash

# Trusty required for Docker
# https://github.com/travis-ci/travis-ci/issues/5448#issuecomment-171420138
dist: trusty

branches:
  only:
    - master

sudo: required

services:
  - docker

# Test all 
matrix:
  include:
    - compiler: "ghc-7.10.3"
      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-2.0,ghc-7.10.3], sources: [hvr-ghc]}}
    - compiler: "ghc-8.0.2"
      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-2.0,ghc-8.0.2], sources: [hvr-ghc]}}
    - compiler: "ghc-8.4.1"
      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-2.2,ghc-8.4.1], sources: [hvr-ghc]}}

install:
  # Docker build
  - docker-compose build --pull
  # Stack setup
  - docker-compose run --rm tests stack --stack-yaml stack.yaml setup
  # Stack clean (Remove any old builds)
  - docker-compose run --rm tests stack --stack-yaml stack.yaml clean

script:
  # Stack build
  - docker-compose run --rm tests stack --stack-yaml stack.yaml build --haddock --no-haddock-deps
  # Stack test (Only non-interactive tests)
  - ./runtests-travis stack.yaml
